// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/d8advisr/BudgetDashboard.tsx": () => import("../components/mockups/d8advisr/BudgetDashboard.tsx"),
  "./components/mockups/d8advisr/CreateGroupPlan.tsx": () => import("../components/mockups/d8advisr/CreateGroupPlan.tsx"),
  "./components/mockups/d8advisr/ExecutionTracker.tsx": () => import("../components/mockups/d8advisr/ExecutionTracker.tsx"),
  "./components/mockups/d8advisr/FeedbackLog.tsx": () => import("../components/mockups/d8advisr/FeedbackLog.tsx"),
  "./components/mockups/d8advisr/FilterModal.tsx": () => import("../components/mockups/d8advisr/FilterModal.tsx"),
  "./components/mockups/d8advisr/HomeDiscovery.tsx": () => import("../components/mockups/d8advisr/HomeDiscovery.tsx"),
  "./components/mockups/d8advisr/InitialPreferences.tsx": () => import("../components/mockups/d8advisr/InitialPreferences.tsx"),
  "./components/mockups/d8advisr/MapView.tsx": () => import("../components/mockups/d8advisr/MapView.tsx"),
  "./components/mockups/d8advisr/NotificationsCenter.tsx": () => import("../components/mockups/d8advisr/NotificationsCenter.tsx"),
  "./components/mockups/d8advisr/PlanDetail.tsx": () => import("../components/mockups/d8advisr/PlanDetail.tsx"),
  "./components/mockups/d8advisr/PlanEdit.tsx": () => import("../components/mockups/d8advisr/PlanEdit.tsx"),
  "./components/mockups/d8advisr/PlanGenerator.tsx": () => import("../components/mockups/d8advisr/PlanGenerator.tsx"),
  "./components/mockups/d8advisr/PlanOverview.tsx": () => import("../components/mockups/d8advisr/PlanOverview.tsx"),
  "./components/mockups/d8advisr/PreferenceEdit.tsx": () => import("../components/mockups/d8advisr/PreferenceEdit.tsx"),
  "./components/mockups/d8advisr/ProfileOverview.tsx": () => import("../components/mockups/d8advisr/ProfileOverview.tsx"),
  "./components/mockups/d8advisr/SignUp.tsx": () => import("../components/mockups/d8advisr/SignUp.tsx"),
  "./components/mockups/d8advisr/VenueDetails.tsx": () => import("../components/mockups/d8advisr/VenueDetails.tsx"),
  "./components/mockups/d8advisr/Welcome.tsx": () => import("../components/mockups/d8advisr/Welcome.tsx")
};
